# Generated by Django 4.2.25 on 2025-10-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenantprofile_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('caretaker', 'Caretaker')], max_length=20),
        ),
    ]
