import type { ButtonHTMLAttributes, ReactNode } from 'react'
import type { Property } from '../types'

export function Button({ className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`rounded-xl bg-forest px-4 py-2.5 font-semibold text-white transition hover:bg-green-900 disabled:opacity-50 ${className}`} {...props} /> }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-green-950/10 bg-white p-5 shadow-card ${className}`}>{children}</section> }
export function Badge({ children, tone = 'green' }: { children: ReactNode; tone?: 'green' | 'gold' | 'red' }) { const styles = { green: 'bg-green-100 text-green-800', gold: 'bg-amber-100 text-amber-900', red: 'bg-red-100 text-red-800' }; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${styles[tone]}`}>{children}</span> }
export function StatCard({ label, value, detail }: { label: string; value: string | number; detail?: string }) { return <Card><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-forest">{value}</p>{detail && <p className="mt-2 text-sm text-slate-500">{detail}</p>}</Card> }
export function PropertyCard({ property }: { property: Property }) { const image = property.images?.find((item) => item.is_cover)?.image ?? property.images?.[0]?.image; return <article className="overflow-hidden rounded-2xl border border-green-950/10 bg-white shadow-card">{image ? <img className="h-44 w-full object-cover" src={image} alt={property.name} /> : <div className="flex h-44 items-center justify-center bg-gradient-to-br from-green-100 to-amber-100 text-4xl">⌂</div>}<div className="p-5"><div className="flex justify-between gap-3"><h3 className="font-bold text-ink">{property.name}</h3><Badge>{property.status}</Badge></div><p className="mt-2 text-sm text-slate-500">📍 {property.neighborhood || property.location}</p><p className="mt-4 text-lg font-bold text-forest">KSh {Number(property.rent_price).toLocaleString()} <span className="text-sm font-normal">/ month</span></p><p className="mt-2 text-sm text-slate-600">🛏 {property.bedrooms} &nbsp; 🚿 {property.bathrooms} &nbsp; · {property.available_units} available</p></div></article> }
export function EmptyState({ children }: { children: ReactNode }) { return <Card className="text-center text-slate-500">{children}</Card> }
