# Generated by Django 4.2.25 on 2025-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_units', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
