import { FormEvent, useState } from 'react'
import type { ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button, Card } from '../components/ui'
import { api } from '../services/api'
import type { Role } from '../types'

const destination = (role: Role) => role === 'owner' ? '/dashboard/landlord' : role === 'agent' || role === 'caretaker' ? '/dashboard/agent' : role === 'admin' ? '/dashboard/admin' : '/dashboard/tenant'
export function Login() { const navigate = useNavigate(); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const user = await api.login(String(form.get('username')), String(form.get('password'))); navigate(destination(user.role)) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in.') } } return <AuthShell title="Welcome back" subtitle="Sign in to your Nyumbani workspace."><form className="space-y-4" onSubmit={submit}><input name="username" required className="field" placeholder="Username" /><input name="password" type="password" required className="field" placeholder="Password" />{error && <p className="text-sm text-red-700">{error}</p>}<Button className="w-full">Log in</Button></form><p className="mt-5 text-sm text-slate-500">New to Nyumbani? <Link className="font-bold text-forest" to="/register">Create an account</Link></p></AuthShell> }
export function Register() { const navigate = useNavigate(); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()) as Record<string, string>; try { await api.register(payload); const user = await api.login(payload.username, payload.password); navigate(destination(user.role)) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create your account.') } } return <AuthShell title="Create your account" subtitle="Find, manage, and make home happen."><form className="space-y-4" onSubmit={submit}><input name="username" required className="field" placeholder="Username" /><input name="email" type="email" required className="field" placeholder="Email" /><input name="phone_number" className="field" placeholder="Phone number (optional)" /><select name="role" className="field"><option value="tenant">Tenant</option><option value="owner">Property owner</option><option value="agent">Agent</option></select><input name="password" type="password" minLength={8} required className="field" placeholder="Password" /><input name="password_confirm" type="password" minLength={8} required className="field" placeholder="Confirm password" />{error && <p className="text-sm text-red-700">{error}</p>}<Button className="w-full">Create account</Button></form><p className="mt-5 text-sm text-slate-500">Already have an account? <Link className="font-bold text-forest" to="/login">Log in</Link></p></AuthShell> }
function AuthShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <main className="grid min-h-screen place-items-center bg-canvas p-5"><Card className="w-full max-w-md"><Link className="text-xl font-extrabold text-forest" to="/">NYUMBANI</Link><h1 className="mt-8 text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-500">{subtitle}</p><div className="mt-8">{children}</div></Card></main> }
