import { useEffect, useState } from 'react'
import { Badge, Card, EmptyState, PropertyCard, StatCard } from '../components/ui'
import { api } from '../services/api'
import type { Maintenance, Payment, Property } from '../types'

function useData() { const [properties, setProperties] = useState<Property[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [maintenance, setMaintenance] = useState<Maintenance[]>([]); useEffect(() => { api.properties().then(setProperties).catch(() => {}); api.payments().then(setPayments).catch(() => {}); api.maintenance().then(setMaintenance).catch(() => {}) }, []); return { properties, payments, maintenance } }
export function LandlordDashboard() { const { properties, payments, maintenance } = useData(); const confirmed = payments.filter((p) => p.status === 'confirmed').reduce((total, p) => total + Number(p.amount), 0); return <div className="space-y-8"><p className="-mt-6 text-slate-500">Here’s what’s happening with your properties.</p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Properties" value={properties.length} detail="Listings in your portfolio" /><StatCard label="Available units" value={properties.reduce((total, p) => total + p.available_units, 0)} detail="Ready for new tenants" /><StatCard label="Rent collected" value={`KSh ${confirmed.toLocaleString()}`} detail="Confirmed payments" /><StatCard label="Maintenance" value={maintenance.length} detail="Open and recent requests" /></div><Card><h2 className="text-lg font-bold">Recent rent payments</h2>{payments.length ? <div className="mt-4 divide-y">{payments.slice(0, 5).map((payment) => <div key={payment.id} className="flex items-center justify-between py-3"><span>Payment #{payment.id}</span><span className="font-semibold">KSh {Number(payment.amount).toLocaleString()}</span><Badge tone={payment.status === 'confirmed' ? 'green' : 'gold'}>{payment.status}</Badge></div>)}</div> : <p className="mt-4 text-slate-500">No payment activity yet.</p>}</Card></div> }
export function TenantDashboard() { const { properties, payments, maintenance } = useData(); const latest = payments[0]; return <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><Card><p className="text-sm font-bold text-gold">YOUR HOME</p><h2 className="mt-2 text-2xl font-bold">{properties[0]?.name ?? 'Your home will appear here'}</h2><p className="mt-2 text-slate-500">{properties[0]?.bedrooms ?? 0} Bedroom · {properties[0]?.location ?? 'Kenya'}</p><div className="mt-8 rounded-xl bg-green-50 p-5"><p className="text-sm text-slate-600">Latest rent payment</p><p className="mt-2 text-3xl font-bold text-forest">{latest ? `KSh ${Number(latest.amount).toLocaleString()}` : 'No rent record yet'}</p>{latest && <p className="mt-2"><Badge tone={latest.status === 'confirmed' ? 'green' : 'gold'}>{latest.status}</Badge></p>}<button className="mt-5 rounded-xl bg-forest px-4 py-2.5 font-semibold text-white">Pay rent</button></div></Card><div className="space-y-5"><StatCard label="Maintenance" value={maintenance.length} detail="Requests in your workspace" /><Card><h2 className="font-bold">Upcoming</h2><p className="mt-3 text-sm text-slate-500">📅 Rent due dates and notifications will appear here.</p></Card></div></div> }
export function AgentDashboard() { const { properties } = useData(); return <div className="space-y-8"><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Listings" value={properties.length} /><StatCard label="Available" value={properties.filter((p) => p.status === 'available').length} /><StatCard label="New inquiries" value="—" detail="Connect inquiry API next" /></div><div><h2 className="mb-4 text-xl font-bold">My listings</h2>{properties.length ? <div className="grid gap-5 md:grid-cols-2">{properties.slice(0, 4).map((property) => <PropertyCard key={property.id} property={property} />)}</div> : <EmptyState>No listings have been assigned yet.</EmptyState>}</div></div> }
export function AdminDashboard() { const { properties, payments } = useData(); return <div className="space-y-7"><p className="-mt-6 text-slate-500">Platform overview and operations health.</p><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Properties" value={properties.length} /><StatCard label="Payments" value={payments.length} /><StatCard label="System status" value="Healthy" /></div><Card><h2 className="font-bold">Administration</h2><p className="mt-3 text-slate-500">Use Django Admin for full user, payment, and notification management while dedicated platform APIs are added.</p></Card></div> }
