# Generated by Django 4.2.25 on 2026-09-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('agent', 'Agent'), ('caretaker', 'Caretaker (legacy)'), ('admin', 'Administrator')], max_length=20),
        ),
    ]
